# Documentation on version 2 compose files can be found below:
# https://docs.docker.com/compose/compose-file/compose-file-v2/

version: '2'
services:
   peer:
     image: jneubaum/honestvote-peer-node:latest 
     environment:
       - EMAIL_ADDRESS=""
       - EMAIL_PASSWORD=""
       - PRIVATE_KEY=""
       - PUBLIC_KEY=""
       - LOGGING=All
     ports:
       - 7002:7002
       - 7003:7003
     logging:
        driver: none
     links:
       - mongo
     depends_on:
       - mongo
   mongo:
     image: mongo:latest
     volumes:
       - /var/lib/docker/volumes/mongo_data
     ports:
       - 27017:27017
     logging:
        driver: none
   client:
     image: jneubaum/honestvote-client:latest
     ports:
       - 8080:8080
     logging:
        driver: none