# Documentation on version 2 compose files can be found below:
# https://docs.docker.com/compose/compose-file/compose-file-v2/

version: '2'
services:
   peer:
     image: jneubaum/honestvote.io-peer-node:latest 
     ipaddress:
     ports:
       - 7002:7002
       - 7003:7003
     links:
       - mongo
     depends_on:
       - mongo
   mongo:
     image: mongo:latest
     ports:
       - 27017:27017